version: "3.9"

services:
  database_creative:
    image: postgres
    container_name: database_creative
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=creative
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: creative
    restart: always
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database_creative
    depends_on:
      - database_creative
volumes:
  pgdata:
    driver: local
